version: '3.8'

services:
  app:
    build: .
    ports:
      - '3333:3333'
    command: yarn start
    links:
      - 'db:database'
  db:
    image: postgres
    ports:
      - '5432:5432'
    restart: always
