import type { NextPage } from 'next'
import Head from 'next/head'

import { withSSRGuest } from '@hocs/withSSRGuest'
import { LoginForm } from '@features/auth/LoginForm'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Admin - Hytzen Shop</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <LoginForm />
    </>
  )
}

export default Home

export const getServerSideProps = withSSRGuest(async () => {
  return {
    props: {},
  }
})
